import { useEffect, useState } from 'react'
import { ArrowRight, ArrowUpRight, BookOpen, BriefcaseBusiness, ChevronRight, CircleDollarSign, FileText, Github, GraduationCap, Linkedin, Mail, Menu, Moon, ShieldCheck, Sparkles, Target, TrendingUp, Trophy, X, Zap } from 'lucide-react'

const resources=[
 {type:'INSIGHTS',title:'CFA Institute — Insights',desc:'Investment thought leadership, research and industry perspectives.',url:'https://www.cfainstitute.org/insights',icon:BookOpen},
 {type:'VALUATION',title:'Equity Valuation: Concepts & Basic Tools',desc:'Intrinsic value, valuation models, multiples and asset-based approaches.',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/equity-valuation-concepts-basic-tools',icon:TrendingUp},
 {type:'ARTICLE',title:'Equity Valuation: Applications & Processes',desc:'Industry analysis, research reports and investment judgment.',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/equity-valuation-applications-and-processes',icon:FileText},
 {type:'CASE STUDY',title:'Institutional Portfolio Management',desc:'Portfolio risk, asset allocation and long-term investment decisions.',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/case-study-portfolio-management-institutional',icon:ShieldCheck},
 {type:'REAL-WORLD CASE',title:'The Rise and Fall of Wirecard',desc:'Financial analysis, governance, red flags and questioning assumptions.',url:'https://rpc.cfainstitute.org/blogs/enterprising-investor/2021/james-h-freis-jr-cfa-the-rise-and-fall-of-wirecard',icon:CircleDollarSign},
]
const skills=['Microsoft Excel','Financial Analysis','Microsoft PowerPoint','Presentation','Canva','Communication','Documentation','Report Management','Teamwork & Collaboration']

function usePage(){const [page,setPage]=useState(()=>location.hash.replace('#/','')||'home');useEffect(()=>{const f=()=>setPage(location.hash.replace('#/','')||'home');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return page}
function Nav({mobile,setMobile}){const links=[['about','About'],['experience','Experience'],['resources','Resources'],['skills','Skills']];return <><header className="nav"><a className="brand" href="#/home">RJ<span>.</span></a><nav>{links.map(([p,l])=><a key={p} href={`#/${p}`}>{l}</a>)}</nav><div className="nav-actions"><a className="icon-link" href="https://www.linkedin.com/in/rishabh-jain-520683393" target="_blank"><Linkedin size={17}/></a><a className="nav-cta" href="#/contact">Let's connect <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>{mobile&&<div className="mobile-menu">{links.map(([p,l])=><a onClick={()=>setMobile(false)} key={p} href={`#/${p}`}>{l}<ArrowRight size={16}/></a>)}<a onClick={()=>setMobile(false)} href="#/contact">Contact <ArrowRight size={16}/></a></div>}</>}
function Shell({children}){const [mobile,setMobile]=useState(false);return <div><Nav mobile={mobile} setMobile={setMobile}/>{children}<footer><div className="footer-brand">RJ<span>.</span></div><p>Building a career in capital.</p><div className="footer-links"><a href="https://www.linkedin.com/in/rishabh-jain-520683393" target="_blank">LinkedIn</a><a href="mailto:rishabhjain@example.com">Email</a></div></footer></div>}
function Home(){return <><section className="hero"><div className="hero-grid"><div><div className="kicker"><span className="dot"/> FINANCE & INVESTMENT · BENGALURU</div><h1>Building a career in <em>capital.</em></h1><p className="lead">I'm Rishabh Jain, a BCom (Finance & Investment) student at Christ University exploring investment banking, financial markets and corporate finance.</p><div className="actions"><a className="button primary" href="#/about">Explore profile <ArrowRight size={16}/></a><a className="button" href="https://www.linkedin.com/in/rishabh-jain-520683393" target="_blank"><Linkedin size={16}/> LinkedIn</a></div><div className="mini-stats"><div><strong>92%</strong><span>Class XII</span></div><div><strong>90%</strong><span>Class X</span></div><div><strong>01</strong><span>Year · Christ</span></div></div></div><div className="hero-card"><div className="card-top"><span>01 / PROFILE</span><Sparkles size={16}/></div><div className="monogram">RJ</div><p>Finance & Investment</p><div className="card-bottom"><span>Future Investment Banker</span><span>2026 ↗</span></div></div></div></section><section className="marquee"><span>FINANCE</span><i>✦</i><span>MARKETS</span><i>✦</i><span>VALUATION</span><i>✦</i><span>INVESTMENT BANKING</span><i>✦</i><span>CORPORATE FINANCE</span></section><section className="preview"><div className="section-head"><div><span className="eyebrow">01 — PROFILE</span><h2>Curious by nature.<br/><em>Finance by direction.</em></h2></div><a href="#/about" className="text-link">Read my story <ArrowUpRight size={16}/></a></div><div className="feature-grid"><div className="feature large"><GraduationCap size={22}/><span>EDUCATION</span><h3>Christ University</h3><p>BCom (Finance & Investment)<br/>Yeshwanthpur · 1st Year</p></div><div className="feature"><Target size={22}/><span>CAREER DIRECTION</span><h3>Investment Banking</h3><p>Building a foundation across valuation, markets and corporate finance.</p></div><div className="feature"><BriefcaseBusiness size={22}/><span>EXPERIENCE</span><h3>Kairos</h3><p>Documentation Wing · Reports & portfolios</p></div></div></section></>}
function About(){return <Page title="About" kicker="02 — ABOUT" intro="A closer look at the person behind the portfolio."><div className="about-layout"><div><p className="big-copy">I’m interested in the mechanics behind businesses, the numbers that explain them, and the decisions that turn information into value.</p><p className="muted">My BCom (Finance & Investment) journey at Christ University is where I’m building that foundation. I’m particularly drawn to investment banking, financial markets, valuation and corporate finance.</p></div><div className="quote-card"><Sparkles size={20}/><p>“Strong careers are built one skill, one project and one thoughtful question at a time.”</p></div></div><div className="stats-row"><div><b>92%</b><span>Class XII · State Board</span></div><div><b>90%</b><span>Class X · CBSE</span></div><div><b>3</b><span>Languages</span></div><div><b>2</b><span>Competitive sports</span></div></div></Page>}
function Experience(){return <Page title="Experience" kicker="03 — EXPERIENCE" intro="Early experiences that are shaping how I work."><div className="experience-card"><div className="exp-number">01</div><div><span className="eyebrow">2026 — PRESENT</span><h3>Kairos — Classroom to Boardroom</h3><p className="role">Documentation Wing Member</p><p className="muted">Managing reports and portfolios, supporting documentation, and maintaining organized records. The role has strengthened my attention to detail, ownership and ability to work within a team.</p><div className="pill-row"><span>Reports</span><span>Portfolios</span><span>Documentation</span><span>Teamwork</span></div></div></div><div className="principles"><div><Zap size={20}/><h3>Ownership</h3><p>Take responsibility for the quality of the work.</p></div><div><ShieldCheck size={20}/><h3>Precision</h3><p>Keep information structured, clear and dependable.</p></div><div><Trophy size={20}/><h3>Consistency</h3><p>Build strong habits that compound over time.</p></div></div></Page>}
function Resources(){return <Page title="Resources" kicker="04 — RESOURCES" intro="A curated reading desk for markets, valuation and real-world finance."><div className="resource-grid">{resources.map((r,i)=>{const I=r.icon;return <a className="resource-card" href={r.url} target="_blank" key={r.title}><div className="resource-icon"><I size={20}/></div><div className="resource-meta"><span>{r.type}</span><span>0{i+1}</span></div><h3>{r.title}</h3><p>{r.desc}</p><div className="resource-arrow">Read resource <ArrowUpRight size={16}/></div></a>})}</div><div className="resource-note"><BookOpen size={20}/><div><b>Learning note</b><p>These are external educational resources. I’m using them as a starting point for building deeper finance knowledge.</p></div></div></Page>}
function Skills(){return <Page title="Skills" kicker="05 — TOOLKIT" intro="The practical toolkit I’m developing alongside my degree."><div className="skills-panel"><div><span className="eyebrow">CURRENT TOOLKIT</span><h3>Tools, communication & analytical habits.</h3></div><div className="skill-list">{skills.map((s,i)=><div key={s}><span>0{i+1}</span><b>{s}</b><ChevronRight size={17}/></div>)}</div></div><div className="beyond"><div><span className="eyebrow">BEYOND FINANCE</span><h3>Football · State-level Taekwondo · English · Hindi · Kannada</h3></div><p>Teamwork, discipline and consistency are skills too.</p></div></Page>}
function Contact(){return <Page title="Let's connect." kicker="06 — CONTACT" intro="Always open to conversations around finance, markets, opportunities and learning."><div className="contact-panel"><div><span className="eyebrow">GET IN TOUCH</span><h3>Let’s talk about<br/><em>finance & ideas.</em></h3></div><div className="contact-actions"><a className="button primary" href="https://www.linkedin.com/in/rishabh-jain-520683393" target="_blank"><Linkedin size={17}/> Connect on LinkedIn</a><a className="button" href="mailto:rishabhjain@example.com"><Mail size={17}/> Send an email</a><a className="button" href="https://github.com/rishabhinevitable/MYINEVITABLEWEBSITE" target="_blank"><Github size={17}/> GitHub</a></div></div></Page>}
function Page({title,kicker,intro,children}){return <main className="page"><div className="page-hero"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{intro}</p></div>{children}</main>}
function App(){const page=usePage();let C={home:Home,about:About,experience:Experience,resources:Resources,skills:Skills,contact:Contact}[page]||Home;return <Shell><C/></Shell>}
export default App
